services:

  merx-scanner:
    build: .
    env_file: .env
    environment:
      - PLATFORMS=Merx
    volumes:
      - //c/Users/tatia/OneDrive/AlleyneAdmAgent/criteria-manager/criteria-manager/data:/data
      - ./known_clients.json:/app/known_clients.json
      - ./results:/results
    restart: "no"

  biddingo-scanner:
    build: .
    env_file: .env
    environment:
      - PLATFORMS=Biddingo
    volumes:
      - //c/Users/tatia/OneDrive/AlleyneAdmAgent/criteria-manager/criteria-manager/data:/data
      - ./known_clients.json:/app/known_clients.json
      - ./results:/results
    restart: "no"

  bonfire-scanner:
    build: .
    env_file: .env
    environment:
      - PLATFORMS=Bonfire
      - BONFIRE_MIN_DAYS=3
    volumes:
      - //c/Users/tatia/OneDrive/AlleyneAdmAgent/criteria-manager/criteria-manager/data:/data
      - ./known_clients.json:/app/known_clients.json
      - ./results:/results
    restart: "no"

  amci-scanner:
    build: .
    env_file: .env
    environment:
      - PLATFORMS=AMCI
    volumes:
      - //c/Users/tatia/OneDrive/AlleyneAdmAgent/criteria-manager/criteria-manager/data:/data
      - ./known_clients.json:/app/known_clients.json
      - ./results:/results
    restart: "no"

  combiner:
    build: .
    env_file: .env
    environment:
      - PLATFORMS=Merx,Biddingo,Bonfire,AMCI
    volumes:
      - //c/Users/tatia/OneDrive/AlleyneAdmAgent/criteria-manager/criteria-manager/data:/data
      - ./known_clients.json:/app/known_clients.json
      - ./results:/results
    command: python combiner.py
    depends_on:
      merx-scanner:
        condition: service_completed_successfully
      biddingo-scanner:
        condition: service_completed_successfully
      bonfire-scanner:
        condition: service_completed_successfully
      amci-scanner:
        condition: service_completed_successfully
    restart: "no"